/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedClassementRouteImport } from './routes/_authenticated/classement'
import { Route as AuthenticatedDefisRouteImport } from './routes/_authenticated/defis'
import { Route as AuthenticatedJoueursRouteImport } from './routes/_authenticated/joueurs'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedPortefeuilleRouteImport } from './routes/_authenticated/portefeuille'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AuthenticatedDuelsIndexRouteImport } from './routes/_authenticated/duels.index'
import { Route as AuthenticatedDuelsIdRouteImport } from './routes/_authenticated/duels.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassementRoute = AuthenticatedClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDefisRoute = AuthenticatedDefisRouteImport.update({
  id: '/defis',
  path: '/defis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoueursRoute = AuthenticatedJoueursRouteImport.update({
  id: '/joueurs',
  path: '/joueurs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortefeuilleRoute =
  AuthenticatedPortefeuilleRouteImport.update({
    id: '/portefeuille',
    path: '/portefeuille',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDuelsIndexRoute = AuthenticatedDuelsIndexRouteImport.update({
  id: '/duels/',
  path: '/duels/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuelsIdRoute = AuthenticatedDuelsIdRouteImport.update({
  id: '/duels/$id',
  path: '/duels/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/defis': typeof AuthenticatedDefisRoute
  '/joueurs': typeof AuthenticatedJoueursRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/duels/$id': typeof AuthenticatedDuelsIdRoute
  '/duels/': typeof AuthenticatedDuelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/defis': typeof AuthenticatedDefisRoute
  '/joueurs': typeof AuthenticatedJoueursRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/duels/$id': typeof AuthenticatedDuelsIdRoute
  '/duels': typeof AuthenticatedDuelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/classement': typeof AuthenticatedClassementRoute
  '/_authenticated/defis': typeof AuthenticatedDefisRoute
  '/_authenticated/joueurs': typeof AuthenticatedJoueursRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/portefeuille': typeof AuthenticatedPortefeuilleRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/_authenticated/duels/$id': typeof AuthenticatedDuelsIdRoute
  '/_authenticated/duels/': typeof AuthenticatedDuelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/classement'
    | '/defis'
    | '/joueurs'
    | '/messages'
    | '/portefeuille'
    | '/profil'
    | '/tableau-de-bord'
    | '/duels/$id'
    | '/duels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assistant'
    | '/classement'
    | '/defis'
    | '/joueurs'
    | '/messages'
    | '/portefeuille'
    | '/profil'
    | '/tableau-de-bord'
    | '/duels/$id'
    | '/duels'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/classement'
    | '/_authenticated/defis'
    | '/_authenticated/joueurs'
    | '/_authenticated/messages'
    | '/_authenticated/portefeuille'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/_authenticated/duels/$id'
    | '/_authenticated/duels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classement': {
      id: '/_authenticated/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof AuthenticatedClassementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/defis': {
      id: '/_authenticated/defis'
      path: '/defis'
      fullPath: '/defis'
      preLoaderRoute: typeof AuthenticatedDefisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/joueurs': {
      id: '/_authenticated/joueurs'
      path: '/joueurs'
      fullPath: '/joueurs'
      preLoaderRoute: typeof AuthenticatedJoueursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portefeuille': {
      id: '/_authenticated/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof AuthenticatedPortefeuilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duels/': {
      id: '/_authenticated/duels/'
      path: '/duels'
      fullPath: '/duels/'
      preLoaderRoute: typeof AuthenticatedDuelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duels/$id': {
      id: '/_authenticated/duels/$id'
      path: '/duels/$id'
      fullPath: '/duels/$id'
      preLoaderRoute: typeof AuthenticatedDuelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedClassementRoute: typeof AuthenticatedClassementRoute
  AuthenticatedDefisRoute: typeof AuthenticatedDefisRoute
  AuthenticatedJoueursRoute: typeof AuthenticatedJoueursRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPortefeuilleRoute: typeof AuthenticatedPortefeuilleRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedDuelsIdRoute: typeof AuthenticatedDuelsIdRoute
  AuthenticatedDuelsIndexRoute: typeof AuthenticatedDuelsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedClassementRoute: AuthenticatedClassementRoute,
  AuthenticatedDefisRoute: AuthenticatedDefisRoute,
  AuthenticatedJoueursRoute: AuthenticatedJoueursRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPortefeuilleRoute: AuthenticatedPortefeuilleRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedDuelsIdRoute: AuthenticatedDuelsIdRoute,
  AuthenticatedDuelsIndexRoute: AuthenticatedDuelsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
